/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package burp;

public class StartWithExtension {
    public static void main(String[] args) {
        burp.StartBurp.main(args);
    }
}
